In [6]:
#CREATE DATAFRAME

import pandas as pd

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [20]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)

In [3]:
import pandas as pd

In [15]:
pd.read_excel("data.xlsx.xlsx")

      name school  marks
0    vinas    svp     89
1     yash    pps     56
2    ruhsi    svb     23
3    chotu    hhp     78
4    harry    ppn     44
5   naitik    jkb     12
6  darshaK    hdh     46

In [23]:
 pd.read_json("data.json")

     name    lang
0   vinas  python
1  bhagat    java

In [27]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [29]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
#EDA (Exploratory Data Analysis)
df.head()         # First 5 rows
df.tail()         # Last 5 rows
df.info()         # Column info: types, non-nulls
df.describe()     # Stats for numeric columns
df.columns        # List of column names
df.shape          # (rows, columns)

In [32]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [39]:
df.describe() #it specifies meanimum values , maximum values , standard diviation , persentiles etc........

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [43]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [45]:
df.shape

(244, 7)

In [46]:
df['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [51]:
df[["tip","size"]]

      tip  size
0    1.01     2
1    1.66     3
2    3.50     3
3    3.31     2
4    3.61     4
..    ...   ...
239  5.92     3
240  2.00     2
241  2.00     2
242  1.75     2
243  3.00     2

[244 rows x 2 columns]

In [52]:
#selecting rows by an inndex

In [59]:
df.loc[4,'sex']

'Female'

In [62]:
df.iloc[4,6]

np.int64(4)

In [65]:
df.loc[0:3 ,["tip","size"]]

    tip  size
0  1.01     2
1  1.66     3
2  3.50     3
3  3.31     2

In [67]:
#SELECTING PERTICULAR ELEMENTS

In [71]:
df.at[1,"size"] #perticular element by lable

np.int64(3)

In [76]:
df.iat[2,1] #perticular element by proper index

np.float64(3.5)

In [94]:
df[(df["total_bill"]>20)&(df['tip']<2)]

     total_bill   tip     sex smoker  day    time  size
57        26.41  1.50  Female     No  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2

In [97]:
df.query("total_bill >20 and tip<4 ") #in this function we write a human langauge

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
15        21.58  3.92    Male     No   Sun  Dinner     2
19        20.65  3.35    Male     No   Sat  Dinner     3
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
35        24.06  3.60    Male     No   Sat  Dinner     3
48        28.55  2.05    Male     No   Sun  Dinner     3
56        38.01  3.00    Male    Yes   Sat  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
60        20.29  3.21    Male    Yes   Sat  Dinner     2
65        20.08  3.15    Male     No   Sat  Dinner     3
68        20.23  2.01    Male     No   Sat  Dinner     2
72        26.86  3.14  Female    Yes   Sat  Dinner     2
78        22.76  3.00    Male     No  Thur   Lunch     2
89        21.16  3.00    Male     No  Thur   Lunch     2
90        28.97  3.00    Male    Yes   Fri  Dinner     2
91        22.49  3.50    Male     No   Fri  Dinner     2
94        22.75  3.25  Female     No   Fri  Dinner     2
98        21.01  3.00    Male    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
113       23.95  2.55    Male     No   Sun  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
129       22.82  2.18    Male     No  Thur   Lunch     3
131       20.27  2.83  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
157       25.00  3.75  Female     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
165       24.52  3.48    Male     No   Sun  Dinner     3
166       20.76  2.24    Male     No   Sun  Dinner     2
173       31.85  3.18    Male    Yes   Sun  Dinner     2
175       32.90  3.11    Male    Yes   Sun  Dinner     2
179       34.63  3.55    Male    Yes   Sun  Dinner     2
180       34.65  3.68    Male    Yes   Sun  Dinner     4
182       45.35  3.50    Male    Yes   Sun  Dinner     3
184       40.55  3.00    Male    Yes   Sun  Dinner     2
186       20.90  3.50  Female    Yes   Sun  Dinner     3
187       30.46  2.00    Male    Yes   Sun  Dinner     5
192       28.44  2.56    Male    Yes  Thur   Lunch     2
206       26.59  3.41    Male    Yes   Sat  Dinner     3
207       38.73  3.00    Male    Yes   Sat  Dinner     4
208       24.27  2.03    Male    Yes   Sat  Dinner     2
210       30.06  2.00    Male    Yes   Sat  Dinner     3
216       28.15  3.00    Male    Yes   Sat  Dinner     5
219       30.14  3.09  Female    Yes   Sat  Dinner     4
227       20.45  3.00    Male     No   Sat  Dinner     4
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
237       32.83  1.17    Male    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2

In [100]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [119]:
df2 = df[['sex','day']].copy() #.copy function gives me a copy dataframe ok. and don't change in original dataframe like df

In [113]:
df2

        sex   day
0    Female   Sun
1    female   Sun
2      Male   Sun
3      Male   Sun
4    Female   Sun
..      ...   ...
239    Male   Sat
240  Female   Sat
241    Male   Sat
242    Male   Sat
243  Female  Thur

[244 rows x 2 columns]

In [118]:
df2.loc[1,'sex'] = "male"

AttributeError: 'str' object has no attribute 'copy'

In [116]:
df2

        sex   day
0    Female   Sun
1      male   Sun
2      Male   Sun
3      Male   Sun
4    Female   Sun
..      ...   ...
239    Male   Sat
240  Female   Sat
241    Male   Sat
242    Male   Sat
243  Female  Thur

[244 rows x 2 columns]

In [117]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66  female     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]