In [9]:
import pandas as pd

In [11]:
df = pd.read_excel(r"C:\Users\vinas\anaconda project\pandas\data_cleaning_sample.xlsx")

In [13]:
df

     Name    Age        City Geneder              Email  Join date
0    Alice  25.0    New York       F  alice@example.com 2021-01-05
1      Bob  30.0  Lose angel       M    bob@example.com 2022-05-08
2  Charlie   NaN       delhi       M    cahrlie@example 2023-10-08
3    David  22.0      mumbai       M  david@example.com 2024-12-11
4      NaN  28.0       delhi       F    eve@example.com        NaT
5    Alice  25.0    New York       F  alice@example.com 2021-01-05
6    Alice  25.0    New York       F  alice@example.com 2021-01-05
7    david  22.0      mumbai       M  david@example.com 2024-12-11

In [15]:
df.isnull()

   Name     Age   City  Geneder  Email  Join date
0  False  False  False    False  False      False
1  False  False  False    False  False      False
2  False   True  False    False  False      False
3  False  False  False    False  False      False
4   True  False  False    False  False       True
5  False  False  False    False  False      False
6  False  False  False    False  False      False
7  False  False  False    False  False      False

In [16]:
df.isnull().sum()

Name         1
Age          1
City         0
Geneder      0
Email        0
Join date    1
dtype: int64

In [18]:
df.dropna() #remove duplicate rows

   Name    Age        City Geneder              Email  Join date
0  Alice  25.0    New York       F  alice@example.com 2021-01-05
1    Bob  30.0  Lose angel       M    bob@example.com 2022-05-08
3  David  22.0      mumbai       M  david@example.com 2024-12-11
5  Alice  25.0    New York       F  alice@example.com 2021-01-05
6  Alice  25.0    New York       F  alice@example.com 2021-01-05
7  david  22.0      mumbai       M  david@example.com 2024-12-11

In [20]:
df.dropna(axis=1)

         City Geneder              Email
0    New York       F  alice@example.com
1  Lose angel       M    bob@example.com
2       delhi       M    cahrlie@example
3      mumbai       M  david@example.com
4       delhi       F    eve@example.com
5    New York       F  alice@example.com
6    New York       F  alice@example.com
7      mumbai       M  david@example.com

In [22]:
df.fillna(0)

     Name    Age        City Geneder              Email            Join date
0    Alice  25.0    New York       F  alice@example.com  2021-01-05 00:00:00
1      Bob  30.0  Lose angel       M    bob@example.com  2022-05-08 00:00:00
2  Charlie   0.0       delhi       M    cahrlie@example  2023-10-08 00:00:00
3    David  22.0      mumbai       M  david@example.com  2024-12-11 00:00:00
4        0  28.0       delhi       F    eve@example.com                    0
5    Alice  25.0    New York       F  alice@example.com  2021-01-05 00:00:00
6    Alice  25.0    New York       F  alice@example.com  2021-01-05 00:00:00
7    david  22.0      mumbai       M  david@example.com  2024-12-11 00:00:00

In [24]:
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    30.000000
2    25.285714
3    22.000000
4    28.000000
5    25.000000
6    25.000000
7    22.000000
Name: Age, dtype: float64

In [26]:
df.ffill()

     Name    Age        City Geneder              Email  Join date
0    Alice  25.0    New York       F  alice@example.com 2021-01-05
1      Bob  30.0  Lose angel       M    bob@example.com 2022-05-08
2  Charlie  30.0       delhi       M    cahrlie@example 2023-10-08
3    David  22.0      mumbai       M  david@example.com 2024-12-11
4    David  28.0       delhi       F    eve@example.com 2024-12-11
5    Alice  25.0    New York       F  alice@example.com 2021-01-05
6    Alice  25.0    New York       F  alice@example.com 2021-01-05
7    david  22.0      mumbai       M  david@example.com 2024-12-11

In [28]:
df.bfill()

     Name    Age        City Geneder              Email  Join date
0    Alice  25.0    New York       F  alice@example.com 2021-01-05
1      Bob  30.0  Lose angel       M    bob@example.com 2022-05-08
2  Charlie  22.0       delhi       M    cahrlie@example 2023-10-08
3    David  22.0      mumbai       M  david@example.com 2024-12-11
4    Alice  28.0       delhi       F    eve@example.com 2021-01-05
5    Alice  25.0    New York       F  alice@example.com 2021-01-05
6    Alice  25.0    New York       F  alice@example.com 2021-01-05
7    david  22.0      mumbai       M  david@example.com 2024-12-11

In [51]:
df

     Name    Age        City Geneder              Email  Join date
0    Alice  25.0    New York       F  alice@example.com 2021-01-05
1      Bob  30.0  Lose angel       M    bob@example.com 2022-05-08
2  Charlie   NaN       delhi       M    cahrlie@example 2023-10-08
3    David  22.0      mumbai       M  david@example.com 2024-12-11
4      NaN  28.0       delhi       F    eve@example.com        NaT
5    Alice  25.0    New York       F  alice@example.com 2021-01-05
6    Alice  25.0    New York       F  alice@example.com 2021-01-05
7    david  22.0      mumbai       M  david@example.com 2024-12-11

In [32]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7    False
dtype: bool

In [34]:
df.drop_duplicates()

     Name    Age        City Geneder              Email  Join date
0    Alice  25.0    New York       F  alice@example.com 2021-01-05
1      Bob  30.0  Lose angel       M    bob@example.com 2022-05-08
2  Charlie   NaN       delhi       M    cahrlie@example 2023-10-08
3    David  22.0      mumbai       M  david@example.com 2024-12-11
4      NaN  28.0       delhi       F    eve@example.com        NaT
7    david  22.0      mumbai       M  david@example.com 2024-12-11

In [38]:
df[' Name '].str.lower() # Converts all names to lowercase.

KeyError: 'Name'

In [42]:
df["City"].str.contains("delhi",case=False)

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7    False
Name: City, dtype: bool

In [45]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [bob, example.com]
2      [cahrlie, example]
3    [david, example.com]
4      [eve, example.com]
5    [alice, example.com]
6    [alice, example.com]
7    [david, example.com]
Name: Email, dtype: object

In [49]:
df2 = df.dropna().copy()               #TYOECATINF OF AGE

In [58]:
df2["Age"]=df["Age"].fillna(0).astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [56]:
df2

   Name   Age        City Geneder              Email  Join date
0  Alice   25    New York       F  alice@example.com 2021-01-05
1    Bob   30  Lose angel       M    bob@example.com 2022-05-08
3  David   22      mumbai       M  david@example.com 2024-12-11
5  Alice   25    New York       F  alice@example.com 2021-01-05
6  Alice   25    New York       F  alice@example.com 2021-01-05
7  david   22      mumbai       M  david@example.com 2024-12-11